rails/projects/reddit_on_rails/solution/config/routes.rb
RedditOnRails::Application.routes.draw do
  resource :session, only: [:new, :create, :destroy]
  resources :users, only: [:new, :create]
  resources :comments, only: [:create, :show] do
    member do
      post "downvote"
      post "upvote"
    end
  end
  resources :subs, except: [:destroy]
  resources :posts, except: [:destroy, :index] do
    resources :comments, only: [:new]
    member do
      post "downvote"
      post "upvote"
    end
  end

  root to: redirect("/subs")
end

rails/projects/reddit_on_rails/solution/app/models/comment.rb
class Comment < ActiveRecord::Base
  include Votable
  
  validates :body, :author, :post, presence: true

  belongs_to :post, inverse_of: :comments
  belongs_to(
    :author,
    class_name: "User",
    foreign_key: :user_id,
    inverse_of: :comments
  )

  has_many(
    :child_comments,
    class_name: "Comment",
    foreign_key: :parent_comment_id,
    primary_key: :id
  )

  belongs_to(
    :parent_comment,
    class_name: "Comment",
    foreign_key: :parent_comment_id,
    primary_key: :id
  )
end

rails/projects/reddit_on_rails/solution/app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :require_signed_in!, only: [:new, :create]

  def create
    @comment = current_user.comments.new(comment_params)

    if @comment.save
      redirect_to post_url(@comment.post_id)
    else
      flash.now[:errors] = @comment.errors.full_messages
      redirect_to new_post_comment_url(@comment.post_id)
    end
  end

  def new
    @comment = Comment.new(post_id: params[:post_id])
    render :new
  end

  def show
    @comment = Comment.find_by_id(params[:id])
    @new_comment = Comment.new(
      post_id: @comment.post_id, parent_comment_id: @comment.id
    )

    render :show
  end


  def downvote; vote(-1); end
  def upvote; vote(1); end

  private
  def comment_params
    params.require(:comment).permit(:body, :post_id, :parent_comment_id)
  end

  def vote(direction)
    @comment = Comment.find(params[:id])
    @user_vote = UserVote.find_by(
      votable_id: @comment.id, votable_type: "Comment", user_id: current_user.id
    )

    if @user_vote
      @user_vote.update(value: direction)
    else
      @comment.user_votes.create!(
        user_id: current_user.id, value: direction
      )
    end

    redirect_to comment_url(@comment)
  end
end

rails/projects/reddit_on_rails/solution/app/views/comments/_comment.html.erb
<p>
  (<%= comment.votes %>) <%= link_to comment.body, comment_url(comment.id) %>
</p>

<ul>
  <% comments_by_parent[comment.id].each do |child_comment| %>
    <li><%= render("comments/comment",
            comment: child_comment,
            comments_by_parent: comments_by_parent) %></li>
  <% end %>
</ul>

rails/projects/reddit_on_rails/solution/app/views/comments/_form.html.erb
<form action="<%= comments_url %>" method="POST">
  <input
    type="hidden"
    name="authenticity_token"
    value="<%= form_authenticity_token %>">

  <input
    type="hidden"
    name="comment[post_id]"
    value="<%= comment.post_id %>">
  <input
    type="hidden"
    name="comment[parent_comment_id]"
    value="<%= comment.parent_comment_id %>">

  <label>
    Body
    <br>
    <textarea name="comment[body]"><%= comment.body %></textarea>
  </label>
  <br>

  <input type="submit">
</form>

rails/projects/reddit_on_rails/solution/app/views/comments/new.html.erb
<div class="border">
  <h1>New Comment!</h1>

  <%= render "form", comment: @comment %>
</div>

rails/projects/reddit_on_rails/solution/app/views/comments/show.html.erb
<div class="border"
  <%= @comment.body %> by <%= @comment.author.name %><br>
  <%= @comment.votes %> upvotes
  <br><br>

  <%= button_to "Upvote", upvote_comment_url(@comment) %>
  <%= button_to "Downvote", downvote_comment_url(@comment) %>

  <b>Reply to this comment:</b>
  <%= render "form", comment: @new_comment %>
</div>