rails/projects/reddit_on_rails/solution/config/routes.rb
RedditOnRails::Application.routes.draw do
  resource :session, only: [:new, :create, :destroy]
  resources :users, only: [:new, :create]
  resources :comments, only: [:create, :show] do
    member do
      post "downvote"
      post "upvote"
    end
  end
  resources :subs, except: [:destroy]
  resources :posts, except: [:destroy, :index] do
    resources :comments, only: [:new]
    member do
      post "downvote"
      post "upvote"
    end
  end

  root to: redirect("/subs")
end

rails/projects/reddit_on_rails/solution/app/models/sub.rb
class Sub < ActiveRecord::Base

  validates :description, :name, :moderator, presence: true
  validates :name, uniqueness: true

  has_many :post_subs, inverse_of: :sub, dependent: :destroy
  has_many :posts, through: :post_subs, source: :post

  # Using polymorphic assocations without a concern
  # has_many :user_votes, as: :votable, class_name: "UserVote"

  belongs_to(
    :moderator,
    class_name: "User",
    foreign_key: :moderator_id,
    primary_key: :id,
    inverse_of: :subs
  )

  # Without a concern, we have to write a #votes method for each votable class
  # def votes
  #   self.user_votes.sum(:value)
  # end
end

rails/projects/reddit_on_rails/solution/app/controllers/subs_controller.rb
class SubsController < ApplicationController
  before_action :require_signed_in!, except: [:index, :show]
  before_action :require_user_owns_sub!, only: [:edit, :update]

  def index
    @subs = Sub.all
    render :index
  end

  def new
    @sub = Sub.new
    render :new
  end

  def show
    @sub = Sub.find(params[:id])
    render :show
  end

  def create
    @sub = current_user.subs.new(sub_params)
    if @sub.save
      redirect_to sub_url(@sub)
    else
      flash.now[:errors] = @sub.errors.full_messages
      render :new
    end
  end

  def update
    @sub = Sub.find(params[:id])
    if @sub.update(sub_params)
      redirect_to @sub
    else
      flash.now[:errors] = @sub.errors.full_messages
      render :edit
    end
  end

  def edit
    @sub = Sub.find(params[:id])
    render :edit
  end

  private
  def require_user_owns_sub!
    return if Sub.find(params[:id]).moderator == current_user
    render json: "Forbidden", status: :forbidden
  end

  def sub_params
    params.require(:sub).permit(:name, :description)
  end
end

rails/projects/reddit_on_rails/solution/app/views/subs/_form.html.erb
<% action_url = sub.persisted? ? sub_url(sub) : subs_url %>
<% http_method = sub.persisted? ? "PATCH" : "POST" %>

<form action="<%= action_url %>" method="POST">
  <input
    type="hidden"
    name="authenticity_token"
    value="<%= form_authenticity_token %>">
  <input type="hidden" name="_method" value="<%= http_method %>">

  <label>
    Name
    <input name="sub[name]" value="<%= sub.name %>">
  </label>
  <br>

  <label>
    Description
    <textarea name="sub[description]"><%= sub.description %></textarea>
  </label>

  <input type="submit" value="Submit!">
</form>

rails/projects/reddit_on_rails/solution/app/views/subs/edit.html.erb
<div class="border">
  <h1>Edit your Sub</h1>

  <%= render "form", sub: @sub %>
</div>

rails/projects/reddit_on_rails/solution/app/views/subs/index.html.erb
<div class="border">
  <h1>All the Subs!</h1>

  <ul>
    <% @subs.each do |sub| %>
      <li><%= link_to sub.name, sub %><br></li>
    <% end %>
  </ul>
</div>

rails/projects/reddit_on_rails/solution/app/views/subs/new.html.erb
<div class="border">
  <h1>Create a new sub!</h1>
  <%= render "form", sub: @sub %>
</div>

rails/projects/reddit_on_rails/solution/app/views/subs/show.html.erb
<div class="border">
  <h1>
    <%= @sub.name %>
  </h1>


  <b>Description</b>
  <p><%= @sub.description %></p>

  <%= link_to "Make New Post!", new_post_url %>

  <ul>
    <% @sub.posts.each do |post| %>
      <li>(<%= post.votes %>) <%= link_to post.title, post %></li>
    <% end %>
  </ul>

  <%= link_to "Edit", edit_sub_url(@sub) if @sub.moderator == current_user %>
</div>